### PR TITLE
Update for ramp server

### PR DESCRIPTION
**Pull request by lucyleeow**
- Use sklearn pipeline wkfl
- removes raw data files (these will be in the private ramp-data repo)
- minor amendments and file name changes
- minor notebook changes

### CODE REVIEW

**Comment by lucyleeow** [comment]
@agramfort @maikia

**Comment by lucyleeow** [comment]
see #2

**Comment by maikia** [comment]
Are there some data files missing (travis is failing)?

**Comment by maikia** [comment]
LGTM @lucyleeow

**Comment by agramfort** [comment]
thx @lucyleeow

**Pull request merged**
